title: Jiaqi Liang
position: Master of Regional Planning
affiliation: Cornell University
email: jl4274@cornell.edu
keywords: minimal academic
google_scholar: https://scholar.google.com/
github_link: https://github.com/april29liang
linkedin: https://www.linkedin.com/in/jiaqi-liang-b3b1b019a/
avatar: ./assets/img/ljq.jpg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Personal Homepage of Jiaqi Liang
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
